-- Generated [
-- Format      : ECLIPSE keywords (grid properties) (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : aprikhnenko
-- Date        : Monday, September 03 2018 16:11:02
-- Project     : PRIVATE
-- Grid        : PRIVATE
-- Unit system : ECLIPSE-Metric
-- Generated ]
SATNUM                                 -- Generated : Petrel
  249249*1 /
 
ROCKNUM                                -- Generated : Petrel
  249249*1 /
  
EQLNUM                                 -- Generated : Petrel
  249249*1 /