-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : aprikhnenko
-- Date        : Monday, September 03 2018 16:11:02
-- Project     : PRIVATE
-- Generated ]

RPTSCHED                               -- Generated : Petrel
  FIP WELLS /

RPTRST                                 -- Generated : Petrel
  BASIC=3 FLOWS FREQ=12 /

SKIP                                   -- Generated : Petrel
--Default history strategy generated.

ENDSKIP                                -- Generated : Petrel

--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


WELSPECS                               -- Generated : Petrel
--'R-9' is the simulation well name used to describe flow from 'R-9'
--
  R-9 'GROUP 1' 57 32 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  R-9 57 32 2 2 OPEN 1* 12.9836 0.1905 963.657 0 1* Z 5.07981 /
  R-9 57 32 3 3 OPEN 1* 11.7247 0.1905 870.254 0 1* Z 5.08054 /
  R-9 57 32 4 4 OPEN 1* 10.3108 0.1905 765.332 0 1* Z 5.08128 /
  R-9 57 32 5 5 OPEN 1* 11.2118 0.1905 832.245 0 1* Z 5.08202 /
  R-9 57 32 6 6 OPEN 1* 12.3199 0.1905 914.526 0 1* Z 5.08275 /
  R-9 57 32 7 7 OPEN 1* 12.4134 0.1905 921.503 0 1* Z 5.08348 /
  R-9 57 32 8 8 OPEN 1* 11.5089 0.1905 854.384 0 1* Z 5.08421 /
  R-9 57 32 9 9 OPEN 1* 12.2086 0.1905 906.368 0 1* Z 5.08495 /
  R-9 57 32 10 10 OPEN 1* 12.3133 0.1905 914.173 0 1* Z 5.08568 /
  R-9 57 32 11 11 OPEN 1* 12.4145 0.1905 921.718 0 1* Z 5.08641 /
  R-9 57 32 12 12 OPEN 1* 12.5255 0.1905 929.995 0 1* Z 5.08715 /
  R-9 57 32 13 13 OPEN 1* 12.0297 0.1905 893.214 0 1* Z 5.08788 /
  R-9 57 32 14 14 OPEN 1* 12.0579 0.1905 895.337 0 1* Z 5.08862 /
  R-9 57 32 15 15 OPEN 1* 12.9645 0.1905 962.693 0 1* Z 5.08935 /
  R-9 57 32 16 16 OPEN 1* 12.1226 0.1905 900.212 0 1* Z 5.09009 /
  R-9 57 32 17 17 OPEN 1* 11.7912 0.1905 875.631 0 1* Z 5.09083 /
  R-9 57 32 18 18 OPEN 1* 11.4674 0.1905 851.618 0 1* Z 5.09157 /
  R-9 57 32 19 19 OPEN 1* 10.6476 0.1905 790.763 0 1* Z 5.09231 /
  R-9 57 32 20 20 OPEN 1* 9.98068 0.1905 741.261 0 1* Z 5.09304 /
  R-9 57 32 21 21 OPEN 1* 11.4059 0.1905 847.14 0 1* Z 5.09378 /
  R-9 57 32 22 22 OPEN 1* 0.84436 0.1905 62.7148 0 1* Z 5.09452 /
  /

GRUPTREE                               -- Generated : Petrel
  'GROUP 1' FIELD /
  /

WCONHIST                               -- Generated : Petrel
  R-9 OPEN LRAT 18.3992 0.164516 781.968 /
  /

WELTARG                                -- Generated : Petrel
  R-9 BHP 52 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2007 /
  /

WCONHIST                               -- Generated : Petrel
  R-9 OPEN LRAT 95.7903 0.770968 2135.61 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2007 /
  /

WCONHIST                               -- Generated : Petrel
  R-9 OPEN LRAT 21.7125 0.683333 421.5 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2007 /
  /

WCONHIST                               -- Generated : Petrel
  R-9 SHUT LRAT 0 0 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2007 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2007 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2008 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2008 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2008 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2008 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2008 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2008 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2008 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2008 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2008 /
  /

WELSPECS                               -- Generated : Petrel
--'OC-24' is the simulation well name used to describe flow from 'OC-24'
--
  OC-24 'GROUP 1' 72 18 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  OC-24 72 18 1 1 OPEN 1* 11.2359 0.1905 836.143 0 1* Z 5.13355 /
  OC-24 72 18 2 2 OPEN 1* 11.8536 0.1905 882.151 0 1* Z 5.13433 /
  OC-24 72 18 3 3 OPEN 1* 12.2401 0.1905 910.949 0 1* Z 5.1352 /
  OC-24 72 18 4 4 OPEN 1* 12.3132 0.1905 916.425 0 1* Z 5.13598 /
  OC-24 72 18 5 5 OPEN 1* 12.0172 0.1905 894.429 0 1* Z 5.13676 /
  OC-24 72 18 6 6 OPEN 1* 11.6965 0.1905 870.594 0 1* Z 5.13754 /
  OC-24 72 18 7 7 OPEN 1* 0.180709 0.1905 9.42829 0 1* Z 1.55902 /
  OC-24 72 18 8 8 OPEN 1* 0.169524 0.1905 8.8447 0 1* Z 1.55902 /
  OC-24 72 18 9 9 OPEN 1* 0.163765 0.1905 8.54416 0 1* Z 1.55898 /
  OC-24 72 18 10 10 OPEN 1* 0.12613 0.1905 6.58054 0 1* Z 1.55894 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 12.3917 0.176667 179.467 1* 1* 1* 0 /
  /

WELTARG                                -- Generated : Petrel
  OC-24 BHP 52 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2008 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 SHUT LRAT 0 0 0 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2008 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2008 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2009 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2009 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2009 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2009 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2009 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2009 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2009 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2009 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2009 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2009 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2009 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2009 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2010 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2010 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2010 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2010 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2010 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2010 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2010 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2010 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2010 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2010 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2010 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2010 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2011 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2011 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2011 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2011 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2011 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2011 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 56.3567 10.2333 1176.05 1* 1* 1* 0 /
  /

WELTARG                                -- Generated : Petrel
  OC-24 BHP 52 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2011 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 54.4032 14.3871 1292.74 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2011 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 39.2065 10.3387 1340.72 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2011 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 33.0133 10.5467 1388.54 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2011 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 21.7419 7.43226 1094.4 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2011 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 12.74 3.46 468.613 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2011 /
  /

WCONHIST                               -- Generated : Petrel
  OC-24 OPEN LRAT 45.7548 14.2935 954.803 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2012 /
  /

WELSPECS                               -- Generated : Petrel
--'168' is the simulation well name used to describe flow from '168'
--
  '168' 'GROUP 1' 62 36 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  '168' 62 36 3 3 OPEN 1* 0.582378 0.1905 43.326 0 1* Z 5.1274 /
  '168' 62 36 4 4 OPEN 1* 0.547402 0.1905 40.7246 0 1* Z 5.12772 /
  '168' 62 36 5 5 OPEN 1* 0.643863 0.1905 47.9017 0 1* Z 5.12804 /
  '168' 62 36 6 6 OPEN 1* 0.55806 0.1905 41.5191 0 1* Z 5.12848 /
  '168' 62 36 7 7 OPEN 1* 0.541082 0.1905 40.2568 0 1* Z 5.12891 /
  '168' 62 36 8 8 OPEN 1* 0.616998 0.1905 45.9058 0 1* Z 5.12928 /
  '168' 62 36 9 9 OPEN 1* 0.60981 0.1905 45.3717 0 1* Z 5.1296 /
  '168' 62 36 10 10 OPEN 1* 0.653204 0.1905 48.6012 0 1* Z 5.12995 /
  '168' 62 36 11 11 OPEN 1* 0.620427 0.1905 46.1632 0 1* Z 5.13028 /
  '168' 62 36 12 12 OPEN 1* 0.645724 0.1905 48.046 0 1* Z 5.13052 /
  '168' 62 36 13 13 OPEN 1* 0.605467 0.1905 45.0513 0 1* Z 5.13083 /
  '168' 62 36 14 14 OPEN 1* 0.575782 0.1905 42.8437 0 1* Z 5.1314 /
  '168' 62 36 15 15 OPEN 1* 0.118171 0.1905 8.79335 0 1* Z 5.13215 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 7.66774 0 148.447 1* 1* 1* 0 /
  OC-24 OPEN LRAT 70.1323 21.2258 1494.51 1* 1* 1* 0 /
  /

WELTARG                                -- Generated : Petrel
  '168' BHP 52 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 45.0862 0.206897 846.79 1* 1* 1* 0 /
  OC-24 OPEN LRAT 70.6793 21.2138 1395.63 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 31.5419 0.248387 610.645 1* 1* 1* 0 /
  OC-24 OPEN LRAT 75.2355 11.7613 1519.93 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 22.3433 3.47 400.527 1* 1* 1* 0 /
  OC-24 OPEN LRAT 83.1867 9.57667 1676.93 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 57.9548 4.99677 978.658 1* 1* 1* 0 /
  OC-24 OPEN LRAT 90.0581 10.1613 1609.4 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 64.3567 3.54333 1086.34 1* 1* 1* 0 /
  OC-24 OPEN LRAT 90.84 9.06667 1562.45 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 64.9355 2.65806 1096.11 1* 1* 1* 0 /
  OC-24 OPEN LRAT 89.6645 9.18065 1542.23 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 62.7161 2.61613 1072.07 1* 1* 1* 0 /
  OC-24 OPEN LRAT 88.2226 9.83226 1517.43 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 58.43 2.45667 1009.67 1* 1* 1* 0 /
  OC-24 OPEN LRAT 85.96 9.56 1495.37 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 57.4548 2.46774 992.819 1* 1* 1* 0 /
  OC-24 OPEN LRAT 88.7968 9.8871 1527.3 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 43.4267 1.19333 538.863 1* 1* 1* 0 /
  OC-24 OPEN LRAT 88.9133 9.87 1360.21 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2012 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 40.2419 0.835484 445.532 1* 1* 1* 0 /
  OC-24 OPEN LRAT 86.8387 9.63871 1392.62 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 41.3032 0.8 457.416 1* 1* 1* 0 /
  OC-24 OPEN LRAT 87.1645 8.17097 1327.4 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 41.7071 0.864286 367.486 1* 1* 1* 0 /
  OC-24 OPEN LRAT 88.65 8.14286 969.207 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 44.3194 0.9 375.665 1* 1* 1* 0 /
  OC-24 OPEN LRAT 89.1645 8.19032 854.558 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 43.2533 1.33333 366.787 1* 1* 1* 0 /
  OC-24 OPEN LRAT 85.36 10.49 824.737 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 46.171 1.89355 391.529 1* 1* 1* 0 /
  OC-24 OPEN LRAT 81.6355 11.6129 774.148 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 45.7567 0.723333 388.03 1* 1* 1* 0 /
  OC-24 OPEN LRAT 83.66 11.5667 682.667 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '168' OPEN LRAT 48.2839 1.44839 414.029 1* 1* 1* 66.88 /
  OC-24 OPEN LRAT 82.5129 11.2871 673.306 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2013 /
  /

WELSPECS                               -- Generated : Petrel
--'164' is the simulation well name used to describe flow from '164'
--
  '164' 'GROUP 1' 43 33 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  '164' 43 33 6 6 OPEN 1* 4.16977 0.1905 309.259 0 1* Z 5.06511 /
  '164' 43 33 7 7 OPEN 1* 7.41582 0.1905 550.024 0 1* Z 5.06569 /
  '164' 43 33 8 8 OPEN 1* 0.235694 0.1905 12.8056 0 1* Z 1.75006 /
  '164' 43 33 9 9 OPEN 1* 0.243267 0.1905 13.2181 0 1* Z 1.75047 /
  '164' 43 33 10 10 OPEN 1* 7.77344 0.1905 576.597 0 1* Z 5.06741 /
  '164' 43 33 11 11 OPEN 1* 8.84758 0.1905 656.291 0 1* Z 5.06798 /
  '164' 43 33 12 12 OPEN 1* 8.96108 0.1905 664.729 0 1* Z 5.06856 /
  '164' 43 33 13 13 OPEN 1* 8.9434 0.1905 663.437 0 1* Z 5.06913 /
  '164' 43 33 14 14 OPEN 1* 8.46653 0.1905 628.079 0 1* Z 5.06971 /
  '164' 43 33 15 15 OPEN 1* 8.38323 0.1905 621.917 0 1* Z 5.07028 /
  '164' 43 33 16 16 OPEN 1* 9.3086 0.1905 690.587 0 1* Z 5.07086 /
  '164' 43 33 17 17 OPEN 1* 9.37218 0.1905 695.324 0 1* Z 5.07144 /
  '164' 43 33 18 18 OPEN 1* 8.99093 0.1905 667.058 0 1* Z 5.07204 /
  '164' 43 33 19 19 OPEN 1* 0.228775 0.1905 12.4449 0 1* Z 1.7563 /
  '164' 43 33 20 20 OPEN 1* 0.245137 0.1905 13.336 0 1* Z 1.75672 /
  '164' 43 33 21 21 OPEN 1* 7.95914 0.1905 590.558 0 1* Z 5.07376 /
  '164' 43 33 22 22 OPEN 1* 7.73505 0.1905 573.947 0 1* Z 5.07434 /
  '164' 43 33 23 23 OPEN 1* 1.16112 0.1905 86.1589 0 1* Z 5.07491 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 12.3129 2.00968 150.224 /
  '168' OPEN LRAT 54.2387 2.36774 431.829 1* 1* 1* 67.1 /
  OC-24 OPEN LRAT 81.4065 12.9032 664.277 1* 1* 1* 0 /
  /

WELTARG                                -- Generated : Petrel
  '164' BHP 52 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 47.58 5.14 951.6 /
  '168' OPEN LRAT 54.8367 2.28333 452.723 1* 1* 1* 62.29 /
  OC-24 OPEN LRAT 76.73 13.9833 648.803 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 53.2032 5.9 954.987 /
  '168' OPEN LRAT 55.1742 2.3 474.11 1* 1* 1* 0 /
  OC-24 OPEN LRAT 81.8 13.3161 837.632 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 53.75 6.69 847.1 /
  '168' OPEN LRAT 55.0067 2.26333 469.367 1* 1* 1* 0 /
  OC-24 OPEN LRAT 77.9333 12.7067 827.723 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2013 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 53.1839 7.27742 850.406 /
  '168' OPEN LRAT 14.6323 3.7 175.418 1* 1* 1* 0 /
  OC-24 OPEN LRAT 73.1355 11.8871 877.626 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 45.3548 6.18387 761.961 /
  '168' OPEN LRAT 22.8742 2 349.516 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.3129 11.9032 1002.77 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 41.5357 5.67857 768.307 /
  '168' OPEN LRAT 23.0357 2.31429 352.119 1* 1* 1* 0 /
  OC-24 OPEN LRAT 75.6714 11.3143 1150.21 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 42.871 5.84516 812.832 /
  '168' OPEN LRAT 23.4871 2.60323 360.761 1* 1* 1* 0 /
  OC-24 OPEN LRAT 73.6 11.0323 1118.72 1* 1* 1* 74.55 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 43.65 5.87 827.603 /
  '168' OPEN LRAT 23.7467 2.66333 364.75 1* 1* 1* 0 /
  OC-24 OPEN LRAT 75.39 11.2733 1145.93 1* 1* 1* 73.26 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 44.9129 2.94516 851.548 /
  '168' OPEN LRAT 23.7387 2.43226 364.626 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.8194 11.4871 1167.65 1* 1* 1* 73.26 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 37.0933 1.97333 703.29 /
  '168' OPEN LRAT 24.5233 2.41333 376.68 1* 1* 1* 0 /
  OC-24 OPEN LRAT 71.1533 9.72 1081.53 1* 1* 1* 73.22 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 35.871 1.95161 680.113 /
  '168' OPEN LRAT 24.3774 2.40645 374.439 1* 1* 1* 0 /
  OC-24 OPEN LRAT 65.7032 8.95484 998.69 1* 1* 1* 73.22 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 34.3774 1.81613 651.797 /
  '168' OPEN LRAT 22.0065 2.17742 340.826 1* 1* 1* 0 /
  OC-24 OPEN LRAT 69.1194 9.38065 1024.05 1* 1* 1* 73.21 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 29.2633 4.28 611.483 /
  '168' OPEN LRAT 16.3333 5.28667 308.683 1* 1* 1* 0 /
  OC-24 OPEN LRAT 79.7967 3.68667 1107.3 1* 1* 1* 71.92 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 27.8581 4.18387 432.965 /
  '168' OPEN LRAT 16.5129 9.63871 497.516 1* 1* 1* 0 /
  OC-24 OPEN LRAT 80.0065 3.54839 859.726 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 25.6333 3.82667 396.067 /
  '168' OPEN LRAT 18.6933 9.9 584.25 1* 1* 1* 0 /
  OC-24 OPEN LRAT 78.0533 4.11333 674.71 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2014 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 21.6 3.70323 425.781 /
  '168' OPEN LRAT 19.5355 10.2839 218.984 1* 1* 1* 0 /
  OC-24 OPEN LRAT 78.7613 5.1 760.806 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 21.3097 4.23226 509.023 /
  '168' OPEN LRAT 16.2323 9.85161 165.621 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.4516 6.65484 1554.86 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 16.0143 3.94286 400.55 /
  '168' OPEN LRAT 15.8286 9.32143 171.447 1* 1* 1* 0 /
  OC-24 OPEN LRAT 74.6714 4.47143 1520.86 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 11.5548 2.6871 272.385 /
  '168' OPEN LRAT 11.6903 6.58387 193.042 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.3161 4 1543.93 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 10.1 2.4 223.5 /
  '168' OPEN LRAT 11.8233 6.67 189.483 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.7667 4.02333 1560.68 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 13.5194 3.2 199.905 /
  '168' OPEN LRAT 13.1065 7.39355 193.465 1* 1* 1* 0 /
  OC-24 OPEN LRAT 77.2613 4.05484 1620.67 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 9.32 1.15333 134.227 /
  '168' OPEN LRAT 14.1133 6.75333 197.507 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.61 4.01 1642.5 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 9.40968 1.14194 134.968 /
  '168' OPEN LRAT 14.7226 6.91935 196.893 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.1097 4.01613 1649.89 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 10.3065 1.27742 148.206 /
  '168' OPEN LRAT 13.9226 6.36452 178.826 1* 1* 1* 0 /
  OC-24 OPEN LRAT 77.4839 4.37742 1650.12 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 10.64 1.41333 158.453 /
  '168' OPEN LRAT 12.8533 5.77333 176.78 1* 1* 1* 0 /
  OC-24 OPEN LRAT 76.4467 5.6 1440.83 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 11.0452 1.58387 163.361 /
  '168' OPEN LRAT 14.5097 6.66129 224.313 1* 1* 1* 0 /
  OC-24 OPEN LRAT 75.6194 7.14194 2103.88 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 10.9867 1.8 162.347 /
  '168' OPEN LRAT 14.4933 6.85333 243.293 1* 1* 1* 0 /
  OC-24 OPEN LRAT 66.96 15.5067 2103.56 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2015 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 10.029 1.62581 156.526 /
  '168' OPEN LRAT 13.0097 6.19032 226.874 1* 1* 1* 0 /
  OC-24 OPEN LRAT 66.5742 16.6355 2102.09 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 7.93226 2.90968 130.452 /
  '168' OPEN LRAT 11.5226 5.99355 193.406 1* 1* 1* 0 /
  OC-24 OPEN LRAT 54.8516 13.8484 1780.57 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 5.08276 7.61379 116.321 /
  '168' OPEN LRAT 14.1966 8.25862 272.776 1* 1* 1* 0 /
  OC-24 OPEN LRAT 61.9897 15.5379 2147.29 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 5.04194 7.89677 127.467 /
  '168' OPEN LRAT 13.1129 8.39677 287.19 1* 1* 1* 0 /
  OC-24 OPEN LRAT 60.3065 15.1258 2131.82 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 4.68333 7.46 130.39 /
  '168' OPEN LRAT 12.44 7.97333 303.033 1* 1* 1* 0 /
  OC-24 OPEN LRAT 60.46 15.1067 2166.44 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 4.60968 7.68387 150.703 /
  '168' OPEN LRAT 12.8452 8.5871 400.855 1* 1* 1* 0 /
  OC-24 OPEN LRAT 60.2032 15.0419 2150.54 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 4.26667 7.18 142.98 /
  '168' OPEN LRAT 11.7533 7.86 369.787 1* 1* 1* 0 /
  OC-24 OPEN LRAT 60.03 15.09 2087.86 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 3.62903 6.25161 124.052 /
  '168' OPEN LRAT 10.7968 7.49677 333.919 1* 1* 1* 0 /
  OC-24 OPEN LRAT 60.8903 15.2161 1966.16 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 3.02581 5.35484 46.5839 /
  '168' OPEN LRAT 11.4484 8.05806 368.826 1* 1* 1* 0 /
  OC-24 OPEN LRAT 57.0258 14.3645 1847.29 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 3.56 6.32 33.35 /
  '168' OPEN LRAT 12.1867 8.53333 416.567 1* 1* 1* 0 /
  OC-24 OPEN LRAT 58.2 14.6533 1827.13 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 4.34839 7.73548 29.7548 /
  '168' OPEN LRAT 12.9903 9.05161 444.484 1* 1* 1* 0 /
  OC-24 OPEN LRAT 57.8645 14.4258 1767.54 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2016 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 4.32 8.07333 17.02 /
  '168' OPEN LRAT 12.46 8.34667 409.367 1* 1* 1* 0 /
  OC-24 OPEN LRAT 56.3633 16.06 1734.01 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2016 /
  /

WELSPECS                               -- Generated : Petrel
--'167' is the simulation well name used to describe flow from '167'
--
  '167' 'GROUP 1' 34 41 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  '167' 34 41 1 1 OPEN 1* 7.13534 0.1905 530.318 0 1* Z 5.10759 /
  '167' 34 41 2 2 OPEN 1* 8.01831 0.1905 595.97 0 1* Z 5.10849 /
  '167' 34 41 3 3 OPEN 1* 7.96075 0.1905 591.718 0 1* Z 5.1094 /
  '167' 34 41 4 4 OPEN 1* 7.31272 0.1905 543.574 0 1* Z 5.1103 /
  '167' 34 41 5 5 OPEN 1* 6.52892 0.1905 485.333 0 1* Z 5.11121 /
  '167' 34 41 6 6 OPEN 1* 0.00434982 0.1905 0.239117 0 1* Z 1.81115 /
  '167' 34 41 14 14 OPEN 1* 0.0516563 0.1905 2.83123 0 1* Z 1.79542 /
  '167' 34 41 15 15 OPEN 1* 6.95558 0.1905 517.279 0 1* Z 5.12025 /
  '167' 34 41 16 16 OPEN 1* 7.98639 0.1905 593.966 0 1* Z 5.12116 /
  '167' 34 41 17 17 OPEN 1* 8.45803 0.1905 629.071 0 1* Z 5.12206 /
  '167' 34 41 18 18 OPEN 1* 8.07334 0.1905 600.486 0 1* Z 5.12297 /
  '167' 34 41 19 19 OPEN 1* 7.70457 0.1905 573.083 0 1* Z 5.12389 /
  '167' 34 41 20 20 OPEN 1* 2.23241 0.1905 166.059 0 1* Z 5.1248 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 6.07097 11.7226 15.5484 /
  '167' OPEN LRAT 13.8194 3.17742 308.41 /
  '168' OPEN LRAT 11.4806 7.65806 373.89 1* 1* 1* 0 /
  OC-24 OPEN LRAT 53.4161 17.8258 1721.46 1* 1* 1* 0 /
  /

WELTARG                                -- Generated : Petrel
  '167' BHP 52 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 5.60968 12.9258 24.0645 /
  '167' OPEN LRAT 21.9839 3.35484 657.671 /
  '168' OPEN LRAT 4.94839 4.49032 134.139 1* 1* 1* 0 /
  OC-24 OPEN LRAT 53.6581 17.9 1726.03 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '164' OPEN LRAT 11.2826 23.9214 82.7714 /
  '167' OPEN LRAT 17.236 11.2179 259.775 /
  '168' OPEN LRAT 3.58075 8.80714 50.6393 1* 1* 1* 0 /
  OC-24 OPEN LRAT 43.9193 20.9964 1785.19 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '164' SHUT LRAT 0 0 0 /
  '167' OPEN LRAT 28.2917 13.4355 147.826 /
  '168' OPEN LRAT 14.5975 25.0355 445.668 1* 1* 1* 0 /
  OC-24 OPEN LRAT 41.3745 25.9484 1812.51 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 27.2609 12.18 184.267 /
  '168' OPEN LRAT 12.3826 23.2867 383.76 1* 1* 1* 0 /
  OC-24 OPEN LRAT 40.1567 26.5067 1796.36 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 23.4811 9.85484 238.519 /
  '168' OPEN LRAT 9.8429 19.3323 327.774 1* 1* 1* 0 /
  OC-24 OPEN LRAT 38.2497 28.629 1701.59 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 25.9304 9.98333 574.357 /
  '168' SHUT LRAT 0 0 0 1* 1* 1* 0 /
  OC-24 OPEN LRAT 36.7943 28.9367 1642.37 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 26.1571 10.0226 809.435 /
  OC-24 OPEN LRAT 35.3829 31.2194 1535.76 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 26.2412 10.4613 1073.61 /
  OC-24 OPEN LRAT 37.6016 28.4806 1616.35 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 23.5536 11.86 1031.27 /
  '168' OPEN LRAT 5.26667 7.29333 66.64 1* 1* 1* 0 /
  OC-24 OPEN LRAT 38.0667 29.1667 1645.95 1* 1* 1* 0 /
  /

WELTARG                                -- Generated : Petrel
  '168' BHP 52 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 25.0771 12.3839 1131.35 /
  '168' OPEN LRAT 0.479665 7.36129 7.63871 1* 1* 1* 0 /
  OC-24 OPEN LRAT 38.1487 29.371 1667.22 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 23.3507 10.54 969.973 /
  '168' OPEN LRAT 5.2029 21.01 109.173 1* 1* 1* 0 /
  OC-24 OPEN LRAT 39.2117 24.2767 1734.93 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2017 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 30.5582 15.7613 1101.11 /
  '168' OPEN LRAT 5.83732 41.1935 242.713 1* 1* 1* 0 /
  OC-24 OPEN LRAT 20.8864 17.7806 908.255 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2018 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 28.8163 25.129 981.9 /
  '168' OPEN LRAT 6.0561 46.1548 181.3 1* 1* 1* 0 /
  OC-24 OPEN LRAT 21.5315 11.2226 807.132 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2018 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 21.7826 25.7786 743.211 /
  '168' OPEN LRAT 3.80821 50.9643 100.286 1* 1* 1* 0 /
  OC-24 OPEN LRAT 23.7143 7.73571 788.929 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2018 /
  /

WCONHIST                               -- Generated : Petrel
  '167' OPEN LRAT 24.3871 23.9871 783.474 /
  '168' OPEN LRAT 7.58765 34.9419 147.376 1* 1* 1* 0 /
  OC-24 OPEN LRAT 21.0687 12.1774 716.787 1* 1* 1* 0 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2018 /
  /

