-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : aprikhnenko
-- Date        : Monday, September 03 2018 16:10:58
-- Project     : PRIVATE
-- Generated ]

INIT                                   -- Generated : Petrel

--GRIDFILE                               -- Generated : Petrel
--  0 0 /
  
GRIDFILE                               -- Generated : Petrel
  2 1 /

GRIDUNIT                               -- Generated : Petrel
  METRES /

MAPUNITS                               -- Generated : Petrel
  METRES /

MAPAXES                                -- Generated : Petrel
  693994.3204 5196665.182 693994.3204 5197665.182 694994.3204 5197665.182 /

MINPORV                                -- Generated : Petrel
  10 /

PINCH                                  -- Generated : Petrel
  1* 1* 1* 1* ALL /

