-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : aprikhnenko
-- Date        : Monday, September 03 2018 16:11:02
-- Project     : PRIVATE
-- Generated ]

WSTAT                                  -- Generated : Petrel
 /

WWGR                                   -- Generated : Petrel
 /

GWGR                                   -- Generated : Petrel
 /

FWGR                                   -- Generated : Petrel

WWCT                                   -- Generated : Petrel
 /

GWCT                                   -- Generated : Petrel
 /

FWCT                                   -- Generated : Petrel

FRV                                    -- Generated : Petrel

WTHP                                   -- Generated : Petrel
 /

TIMESTEP                               -- Generated : Petrel

FRS                                    -- Generated : Petrel

WVPR                                   -- Generated : Petrel
 /

GVPR                                   -- Generated : Petrel
 /

FVPR                                   -- Generated : Petrel

WVPT                                   -- Generated : Petrel
 /

GVPT                                   -- Generated : Petrel
 /

FVPT                                   -- Generated : Petrel

WVIR                                   -- Generated : Petrel
 /

GVIR                                   -- Generated : Petrel
 /

FVIR                                   -- Generated : Petrel

WVIT                                   -- Generated : Petrel
 /

GVIT                                   -- Generated : Petrel
 /

FVIT                                   -- Generated : Petrel

WPI                                    -- Generated : Petrel
 /

WWPR                                   -- Generated : Petrel
 /

GWPR                                   -- Generated : Petrel
 /

FWPR                                   -- Generated : Petrel

WOPR                                   -- Generated : Petrel
 /

GOPR                                   -- Generated : Petrel
 /

FOPR                                   -- Generated : Petrel

WGPR                                   -- Generated : Petrel
 /

GGPR                                   -- Generated : Petrel
 /

FGPR                                   -- Generated : Petrel

WEPR                                   -- Generated : Petrel
 /

WWPT                                   -- Generated : Petrel
 /

GWPT                                   -- Generated : Petrel
 /

FWPT                                   -- Generated : Petrel

WOPT                                   -- Generated : Petrel
 /

GOPT                                   -- Generated : Petrel
 /

FOPT                                   -- Generated : Petrel

WGPT                                   -- Generated : Petrel
 /

GGPT                                   -- Generated : Petrel
 /

FGPT                                   -- Generated : Petrel

FPR                                    -- Generated : Petrel

FWIP                                   -- Generated : Petrel

FOIPG                                  -- Generated : Petrel

FGIPL                                  -- Generated : Petrel

FOIP                                   -- Generated : Petrel

FOIPL                                  -- Generated : Petrel

FGIP                                   -- Generated : Petrel

FGIPG                                  -- Generated : Petrel

WWIR                                   -- Generated : Petrel
 /

GWIR                                   -- Generated : Petrel
 /

FWIR                                   -- Generated : Petrel

WOIR                                   -- Generated : Petrel
 /

GOIR                                   -- Generated : Petrel
 /

FOIR                                   -- Generated : Petrel

WGIR                                   -- Generated : Petrel
 /

GGIR                                   -- Generated : Petrel
 /

FGIR                                   -- Generated : Petrel

WWIT                                   -- Generated : Petrel
 /

GWIT                                   -- Generated : Petrel
 /

FWIT                                   -- Generated : Petrel

WOIT                                   -- Generated : Petrel
 /

GOIT                                   -- Generated : Petrel
 /

FOIT                                   -- Generated : Petrel

WGIT                                   -- Generated : Petrel
 /

GGIT                                   -- Generated : Petrel
 /

FGIT                                   -- Generated : Petrel

WGOR                                   -- Generated : Petrel
 /

GGOR                                   -- Generated : Petrel
 /

FGOR                                   -- Generated : Petrel

WBHP                                   -- Generated : Petrel
 /

PERFORMA                               -- Generated : Petrel

RPTONLY                                -- Generated : Petrel

